# Setup
title: JH - Data Analyst story
description: Hello! Welcome my github story
url: https://dooryuniverse.github.io/
avatar: /profile_img.jpg
paginate: 5
permalink: pretty
cover_image: /profile_img.jpg

# Gems
plugins:
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap

# Optimize Jekyll
exclude:
  - .editorconfig
  - .git
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md
  - scripts/
  - not-pure-poole.gemspec

# Optimize Jekyl SEO Tag
twitter:
  username: doory114
  card: summary
logo: logo.png
social:
  name: Songzi Vong
  links:
    - https://twitter.com/doory114
    - https://github.com/DOOryUniverse
google_site_verification: xxxxx
lang: en

sass:
  sass_dir: _sass
  style: :compressed

# Options

# Replace this value and uncomment to enable Google Analytics tracking
# google_analytics: UA-000000-0

# Replace this value and uncomment to enable Disqus
# disqus: xxxxxx

# Specify the author for blog posts
author:
  name: JUNG HWAN LEE
  url: https://github.com/DOOryUniverse/
  email: doory114@gmail.com
